# Generated by Django 2.2.9 on 2020-07-18 08:34

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200718_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='address',
            name='formatted',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='raw',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.HashIndex(fields=['formatted'], name='address_add_formatt_854646_hash'),
        ),
    ]
